// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWhvxSz8byw_QOZSykqhFRTn1XFgkeyaQ',
    appId: '1:266027916025:web:3fd6c96b32cc1e5273e028',
    messagingSenderId: '266027916025',
    projectId: 'de04-cd0be',
    authDomain: 'de04-cd0be.firebaseapp.com',
    storageBucket: 'de04-cd0be.appspot.com',
    measurementId: 'G-X1G2459K1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClOCAgM12_Vf_ZMwcHEqskxEGw4eAqYLI',
    appId: '1:266027916025:android:a6fe700acf0bec0273e028',
    messagingSenderId: '266027916025',
    projectId: 'de04-cd0be',
    storageBucket: 'de04-cd0be.appspot.com',
  );
}
